# -*- coding: utf-8 -*-
"""Desafio python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UYV8i6f2DnQb8hxzPrdsMxMg2XEoAeF_

1- Faça um Programa que mostre a média da soma dos números 7, 4, 9, 9, 9, 7, 0, 3, 0, 2, 3. Converta este valor para inteiro e encontrará a senha para o desafio 2, boa sorte.
"""

media = (7+4+9+9+9+7+0+3+0+2+3)/11
print(media)

print (int(media))



"""2- Faça um programa que peça um conjunto de números inteiros entre 0 e 10 (considere o 10), calcule e mostre na tela a quantidade de números pares e a quantidade de números ímpares.
A senha será a quantidade de números ímpares desta sequência.
"""

num=int(input('digite um numero de 0 a 10') )
contpar=0
contimp=0
for i in range(num):
  if i %2 ==0:
    contpar= contpar+1
  else:
    contimp=contimp +1
print(contimp)



"""3- Na fase 3, faça um Programa que peça 5 números (digite quando solicitado: 8, 9, 1, 7 e 28) e imprima o menor, o maior e a média deles. Seu programa deve também somar estes 3 números(menor, maior e média), converta-os para inteiro e imprima "A SENHA PARA A FASE 4 É {coloque aqui o resultado da soma}""""

lista=[]
for i in range(5):
  numero= int(input('digite os numero: '))
  lista.append(numero)
  
minimo = min(lista)
maximo = max(lista)
media = sum(lista)/ len(lista)
total = sum([minimo,maximo,media])
print(minimo)
print(maximo)
print(media)
print(total)
print (int(total))



"""A SENHA PARA A FASE 4 É 39"""



"""4- Nossos sinceros parabéns por chegar até aqui, continue estudando e programando pois ainda não acabou...
Agora faça um Programa que leia seis números(7, 4, 1, 8, 5 e 2), coloque-os em uma lista e mostre-os em ordem decrescente. 
Na linha de baixo imprima a raiz quadrada do número de índice 1 desta lista e então estará pronto para seguir para o próximo desafio.
"""

import math
lista=[]
for i in range(6):
  numero= int(input('digite os numero: '))
  lista.append(numero)
lista= sorted(lista, reverse=True)
print(lista)
print(math.sqrt(lista[1]))
print (int(math.sqrt(lista[1])))



"""5- Opa, já chegou na metade \0/ . Agora faça um programa que leia uma palavra composta por caracteres alfanúméricos (letras e números) e imprima as vogais, consoantes e numeros um abaixo do outro:
VOGAIS: O
CONSOANTES: P,Y,T,H,N
NÚMEROS: 2020

Considere python2020 como a palavra de entrada e retorne como saída as letras em maiúsculas.
Está se perguntando cadê a senha? ela é a própria palavra em maiúscula. Fácil né !? :D
"""

palavra ='python2020'
vogais = []
consoantes = []
numeros=[]
for i in range(len(palavra)):
  if palavra[i]   in 'aeiou':
    vogais.append(palavra[i])
  elif palavra[i] in '0123456789':
    numeros.append(palavra[i])
  else:
    consoantes.append(palavra[i])
vogais= "".join(vogais).upper()
numeros = "".join(numeros).upper()
consoantes = ",".join(consoantes).upper()
#print(vogais)
#print(numeros)
#print(consoantes)
print(f'VOGAIS: {vogais} CONSOANTES: {consoantes}  NÚMEROS: {numeros}' )
print(f'Senha: {palavra.upper()}')



"""6- Faça um programa que adivinhe a senha para o próximo desafio. Como?? Simples!

1º passo: Peça um número qualquer do usuário, qualquer número mesmo, o que ele pensar na hora.

2º passo: Multiplique este número digitado por 2.

3º passo: Some a resposta com 8.

4º passo: Divida o resultado por 2

5º passo: Diminua o número que o usuário digitou no início.

Abracadabra!!! Faça isso e seu programa encontrará a senha.
"""

numero =  int(input('Digite um numero: '))
numero= (((numero*2)+8)/2)-numero
print(f'senha: {int(numero)}')



"""7- Crie uma lista com as idades e alturas de 20 clientes. Faça um Programa que determine quantos clientes com mais de 18 anos possuem altura inferior à média de altura desses clientes. A resposta deverá retornar um número inteiro. Em seguida insira este número no desafio anterior e novamente o programa dirá a senha para o próximo desafio."""

cliente={}
dicionario= []
soma =0
soma1 = 0
media =0
for i in range(20):
  cliente.clear()
  cliente['idade']= int(input('idade: '))
  cliente['altura']= float(input('altura: '))
  soma = soma + cliente['altura']
  #dicionario[idade]=idade
  #dicionario[altura]=altura
  dicionario.append(cliente.copy())
#print(dicionario)
media = soma/len(dicionario)
#print(media)
for p in dicionario:
  if p['idade']>=18:
    if p['altura']<media:
      soma1+=1
print(f'Foi cadastrados {soma1} clientes que tem altura inferior a media')

#media = sum(dicionario[altura])/len(dicionario[altura])
#print(media)

"""8- Faça um programa que peça um número inteiro(Considere o número 100) e determine se ele é ou não um número primo. Um número primo é aquele que é divisível somente por ele mesmo e por 
1. Caso este número não seja primo, imprima na tela também o maior número primo antes dele.
Exemplo:
Insira um número: (100)
Este número: é(ou não) primo
A senha para o desafio 9 é: {}
"""

import math
primos=[]
def primo(n):
  raiz = int(math.sqrt(n))
  for d in range(2, raiz +1):
    if n % d ==0:
      return False
  return True


numero = int(input('Digite um numero: '))
if primo(numero):
  print(f'o numero {numero} é primo')
  
else:  
  print(f'o numero {numero} não é primo')
  for x in range(1,numero):
    if primo(x):
      primos.append(x)
  print(f'{max(primos)} É o maior número primo antes do {numero}' )
  print(f'A senha para o desafio 9 é: {max(primos)}')

"""9- Continue codando, você está quase lá :D. Agora faça um programa que calcule o fatorial de um número inteiro fornecido pelo usuário. Ex.: 5!=5.4.3.2.1=120. A saída deve ser conforme o exemplo abaixo:
Considere o número 7
7! = 7. 6 . 5 . 4 . 3 (...) = {senha}
"""

numero = int(input('Digite um numero: '))
c= numero
f= 1
print(f'{numero}! = ',end='')
while c>0:
  print(f'{c}',end='')
  print(f' . ' if c>1 else ' = ', end='')
  f*=c
  c-=1
print(f'{f}')

"""10- Faça um programa que leia um número indeterminado de valores, correspondentes a notas, encerrando a entrada de dados quando for informado um valor igual a -1 (que não deve ser armazenado). Após esta entrada de dados, faça:
Mostre a quantidade de valores que foram lidos;
Exiba todos os valores na ordem em que foram informados, um ao lado do outro;
Exiba todos os valores na ordem inversa à que foram informados, um ao lado do outro;
Calcule e mostre a soma dos valores;
Calcule e mostre a média dos valores;
Calcule e mostre a quantidade de valores acima da média calculada;
Calcule e mostre a quantidade de valores abaixo de sete;
Encerre o programa com a mensagem EU VENCI \O/
"""

nota=[]
while True:
  n = str(input('Digite as notas: '))
  if n == '-1':
    break
  else:
    n=int(n)
    nota.append(n)
#print(nota)
print(f'Quantidade de valores lidos é: {len(nota)}')
print(f'Em Ordem que foram informados: {nota}')
print(f'Em Ordem inversa que foram informados: {nota[::-1]}')
print(f'Em Ordem que crescente: {sorted(nota)}')
print(f'Em Ordem que decrescente: {sorted(nota,reverse=True)}')
print(f'Soma dos valores é: {sum(nota)}')
media = sum(nota)/len(nota)
print(f'Media dos valores é: {media}')
cont =0
for i in nota:
  if i > media:
    cont+=1
print(f'Quantidade de valores acima da media é {cont}')
cont1 =0
for j in nota:
  if j < 7:
    cont1+=1
print(f'Quantidade de valores abaixo de 7 é {cont1}')

print(' EU VENCI \O/')